// export const products = [
//   {
//     id: 1,
//     title: "Samsung S21",
//     description: "black in color",
//     price: "2500",
//     img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
//     quantity: 1,
//   },
//   {
//     id: 2,
//     title: "Samsung M21",
//     description: "white in color",
//     price: "2300",
//     img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
//     quantity: 1,
//   },
//   {
//     id: 3,
//     title: "Redmi 9",
//     description: "black in color",
//     price: "3500",
//     img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
//     quantity: 1,
//   },
//   {
//     id: 4,
//     title: "Iphone 12",
//     description: "Best mobile ever",
//     price: "90500",
//     img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
//     quantity: 1,
//   },
//   {
//     id: 5,
//     title: "Samsung S21",
//     description: "black in color",
//     price: "2500",
//     img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
//     quantity: 1,
//   },
//   {
//     id: 6,
//     title: "Redmi 9",
//     description: "black in color",
//     price: "3500",
//     img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
//     quantity: 1,
//   },
//   {
//     id: 7,
//     title: "Samsung S21",
//     description: "black in color",
//     price: "2500",
//     img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
//     quantity: 1,
//   },
//   {
//     id: 8,
//     title: "Iphone 12",
//     description: "Best mobile ever",
//     price: "90500",
//     img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
//     quantity: 1,
//   },
//   {
//     id: 9,
//     title: "Samsung S21",
//     description: "black in color",
//     price: "2500",
//     img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
//     quantity: 1,
//   },
// ];

export const products = [
  {
    id: 1,
    title: "Fjallraven - Foldsack No. 1 Backpack",
    description: "Your perfect pack for everyday use",
    price: "109.95",
    img: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    quantity: 1,
    category: "men's clothing",
    
  },
  {
    id: 2,
    title: "Mens Casual Premium Slim Fit T-Shirts ",
    price: "22.3",
    description: "Slim-fitting style, light weight & soft fabric",
    category: "men's clothing",
    img: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    price: "55.99",
    description: "great outerwear jackets for Spring/Autumn/Winter",
    category: "men's clothing",
    img: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Mens Casual Slim Fit",
    price: "15.99",
    description: "The color could be slightly different between on the screen and in practice.",
    category: "men's clothing",
    img: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Gold & Silver Chain Bracelet",
    price: "695",
    description: "the Naga was inspired by the mythical water dragon",
    category: "jewelery",
    img: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Solid Gold Petite Micropave ",
    price: "168",
    description: "Designed and sold by Hafeez Center in the United States",
    category: "jewelery",
    img: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "White Gold Plated Princess",
    price: "9.99",
    description: "Classic Wedding Engagement Diamond Promise Ring for Her.",
    category: "jewelery",
    img: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "Gold Plated Stainless Steel Double",
    price: "10.99",
    description: "Rose Gold Plated Double Flared Tunnel Plug Earrings.",
    category: "jewelery",
    img: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "WD 2TB Portable External Hard Drive",
    price: "64",
    description: "USB 3.0 and USB 2.0 Compatibility.",
    category: "electronics",
    img: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    quantity: 1,
  },
  {
    id: 10,
    title: "SanDisk SSD PLUS 1TB Internal SSD",
    price: "109",
    description: "Easy upgrade for faster boot up, shutdown",
    category: "electronics",
    img: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    quantity: 1,
  },
]
